#!/usr/bin/env bash
# sync-portraits.sh — vendor the gnome portrait set into the portal.
#
# The canonical portraits are generated on the platform control repo's
# `full-cast-renders` branch (igotchi/staging/renders/<gnome>/illus1..5.png,
# one per craft-ladder stage; guidance: platform igotchi/illustrations.md).
# The design law says they eventually ship IN THE THEME (§8) as a release; until
# that release train runs, the portal vendors them directly so the Gnomes page
# can show them now. This script re-pulls them and regenerates the
# availability manifest the profile card reads (_data/gnome_portraits.yml).
#
# Usage: scripts/sync-portraits.sh [platform-worktree-or-checkout]
#   arg = a local path to a platform checkout on the full-cast-renders branch.
#   Defaults to ../platform (adjust for your layout).
#
# Portraits carry a baked-in white background and their signature accent; per
# platform illustrations.md §3 the accent NEVER colours portal UI — the card
# chrome stays neutral theme ink and the portrait supplies all colour.
set -euo pipefail

WWW_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PLATFORM="${1:-$WWW_ROOT/../platform}"
SRC="$PLATFORM/igotchi/staging/renders"
DST="$WWW_ROOT/assets/gnomes"

if [ ! -d "$SRC" ]; then
  echo "sync-portraits: no renders at $SRC" >&2
  echo "  point arg 1 at a platform checkout on the full-cast-renders branch" >&2
  exit 1
fi

rm -rf "$DST"
mkdir -p "$DST"
copied=0
for d in "$SRC"/gn_*; do
  [ -d "$d" ] || continue
  g="$(basename "$d")"
  # only vendor a gnome with a COMPLETE five-stage set
  n=$(find "$d" -maxdepth 1 -name 'illus[1-5].png' | wc -l | tr -d ' ')
  [ "$n" = "5" ] || { echo "skip $g ($n/5 stages)"; continue; }
  mkdir -p "$DST/$g"
  for i in 1 2 3 4 5; do cp "$d/illus$i.png" "$DST/$g/illus$i.png"; copied=$((copied+1)); done
done

OUT="$WWW_ROOT/_data/gnome_portraits.yml"
{
  echo "# gnome_portraits.yml — GENERATED by scripts/sync-portraits.sh."
  echo "# Gnomes with a committed portrait set (assets/gnomes/<name>/illus1..5.png,"
  echo "# one per craft-ladder stage). The profile card renders the stage-"
  echo "# appropriate portrait for any gnome listed here; others fall back to the"
  echo "# igotchi text glyph. Source: platform full-cast-renders branch."
  echo "gnomes:"
  for d in "$DST"/gn_*; do [ -d "$d" ] && echo "  - $(basename "$d")"; done
} > "$OUT"

echo "sync-portraits: vendored $copied images for $(find "$DST" -maxdepth 1 -type d -name 'gn_*' | wc -l | tr -d ' ') gnomes"
echo "sync-portraits: wrote $OUT"
